desc "Add Branch keys and Universal Link domains to BranchPluginExample"
lane :update do
  # This app is not currently set up properly for test in the Dashboard. Don't include
  # :test_key in the project for now.
  setup_branch live_key: "key_live_feebgAAhbH9Tv85H5wLQhpdaefiZv5Dv",
     # test_key: "key_test_hdcBLUy1xZ1JD0tKg7qrLcgirFmPPVJc",
     app_link_subdomain: "bnctestbed",
             uri_scheme: "branchtest",
   android_project_path: "examples/android/BranchPluginExample",
              xcodeproj: "examples/ios/BranchPluginExample/BranchPluginExample.xcodeproj",
                 commit: true
end

desc "Validate Universal Link settings for a project"
lane :validate do
  # The :domains parameter is optional.
  # Without it, validation passes if at least one domain exists in the project and
  # all domains pass validation.
  # With this parameter, the applinks: domains in the project must match this list.
  # Order is irrelevant.
  # This app is not currently set up properly for test in the Dashboard. Don't include
  # test domains in the project for now.
  validate_universal_links domains: %w{
    bnctestbed.app.link
    bnctestbed-alternate.app.link
  }
end
