desc "Add Branch keys and Universal Link domains to BranchPluginExample"
lane :setup do
  setup_branch
end

desc "Add Branch keys and Universal Link domains to BranchPluginExample and commit to Git"
lane :setup_and_commit do
  setup_branch commit: true # Use a string here for a custom commit message
end

desc "Set up the BranchPluginExampleObjc"
lane :setup_objc do
  setup_branch xcodeproj: "examples/ios/BranchPluginExampleObjc/BranchPluginExampleObjc.xcodeproj"
end

desc "Set up the BranchPluginExampleCarthage"
lane :setup_carthage do
  setup_branch xcodeproj: "examples/ios/BranchPluginExampleCarthage/BranchPluginExampleCarthage.xcodeproj"
end

desc "Validate Universal Link settings for a project"
lane :validate do
  # The :domains parameter is optional.
  # Without it, validation passes if at least one domain exists in the project and
  # all domains pass validation.
  # With this parameter, the applinks: domains in the project must match this list.
  # Order is irrelevant.
  # This app is not currently set up properly for test in the Dashboard. Don't include
  # test domains in the project for now.
  validate_universal_links domains: %w{
    bnctestbed.app.link
    bnctestbed-alternate.app.link
  }
end
